#!/usr/bin/env bash
# Installs Nginx and config

sudo apt-get update -y
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Holberton School" > sudo tee /etc/nginx/html/index.html

sudo service nginx restart
