#!/bin/bash
.TH man 7 "19 Sep 2019" "holberton man page"
.SH NAME
holberton - become a full-stack software engineer 
.SH SYNOPSIS
holberton [STUDENTNAME]
.SH DESCRIPTION
Holberton Shcool is a project-based alternative to collage for the next generation of software engineers.
.SH OPTIONS
.B holberton does not take any options. However, you can supply studentname
.SH SEE ALSO
.I peerlearning(2), projetbased(2), fullstack(2), Betty(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Julien Barbier, Sylvian Kalache, Sophie Barbier, Guillaume Salva, Kris Bredemeier, Julien Cyr, Alex Gautier and all the Holberton mentors
